### ISSUE TITLE
ISSUE-002: Update background image

### ISSUE THREAD

**Issue by anavatya** [anavatya/Chrome-Quotes#11]
Describe the issue

Update the color of the background to a linear gradient between #A1BEEA and #D0D3C9

```background-image: linear-gradient(to bottom, #a1beea, #94c9df, #a3cfce, #bcd1c5, #d0d3c9);```

Additional context

Please attach a screenshot of the gradient so that we can merge it.

**Comment by mayank1784** [comment]
Hey! I will able to work on the issue. Kindly assign me
