### ISSUE TITLE
ISSUE-003: Add more quotes

### ISSUE THREAD

**Issue by anavatya** [anavatya/Chrome-Quotes#13]
Describe the issue
Add quotes with a nature image in the background folder.

Additional Context
1. image should be named backgroundX.jpg (follow the numbering in the backgrounds folder)
2. No. of quotes added should be equal to the number of images so that each quote has a different backgound.

**Comment by mayank1784** [comment]
I will work on it within 2hrs. Kindly assign

**Comment by akhilrao2797** [comment]
Can you please assign this to me
