### ISSUE TITLE
ISSUE-006: Rounded Corner Button

### ISSUE THREAD

**Issue by anavatya** [anavatya/Chrome-Quotes#16]
Describe the issue
Change the button to have rounded corners.

Additional context
Sample button
<img width="222" alt="Screenshot 2023-10-23 at 2 05 16 PM" src="https://github.com/anavatya/Chrome-Quotes/assets/18523147/ca64a725-a2c2-4071-92ab-d3167f9592ab">

**Comment by Virtual4087** [comment]
I would like to work on this
