### ISSUE TITLE
ISSUE-001

### ISSUE THREAD

**Issue by anavatya** [anavatya/Chrome-Quotes#9]
Describe the issue
Update the readme file with clear and concise information on what this repo is for.

Additional context
This repo contains code for a manifest v3 chrome extension which on clicking will show a quote with an image below. It also has a change quote button on clicking which the quote and image will change.

**Comment by aks057** [comment]
@anavatya Can I do it?

**Comment by aks057** [comment]
@anavatya please review the code

**Comment by anavatya** [comment]
PR : #12 reviewed and merged
